
const itemList = [
    {
        id: '10001',
        imgSrc: 'cat_treat_01.jpg',
        imgAlt: 'A cat is smelling the treat ball in a tray.', 
        productDetails: {
            name: 'Bravo Healthy Bites',
            category: 'treat',
            price: 19.29,
            review: '4.5',
            amountOfReviews: '129',
            description: "It's natural for cats to crave flavor and variety in their diet. They’re obligate carnivores, which means they must consume a high protein diet to thrive. That’s why we offer a range of healthy, 100% poultry and seafood treats that are custom formulated to meet the nutritional needs of cats. They’re sure to entice even the most purrsnickety feline.",
        },
    },
    {
        id: '10002',
        imgSrc: 'cat_treat_02.jpg',
        imgAlt: 'Two cat lick the treat lolly.', 
        productDetails: {
            name: 'Bravo Tasty Treat Lolly',
            category: 'treat',
            price: 12.99,
            review: '4.9',
            amountOfReviews: '289',
            description: "This bundle includes everything you need to get your cats started with the Boredom Buster Licking Mat. Inaba Churu and Nulo Perfect Puree treats are the ideal accompaniments to the slow feeder licking mat. Combined, the trio helps to alleviate boredom, reduce anxiety, and combat stress while improving mental and digestive health. ",
        },
    },
    {
        id: '10003',
        imgSrc: 'cat_treat_03.jpg',
        imgAlt: 'A cat is licking the treat.', 
        productDetails: {
            name: 'Lickable Treat',
            category: 'treat',
            price: 20.99,
            review: '4.9',
            amountOfReviews: '399',
            description: "These lickable treats are available in five delectable varieties. Churu Purées are high in the moisture that felines need for health. Simply tear open a tube and give it a little squeeze to feed these grain-free, preservative-free treats by hand. You can also pour them into a bowl or use as a tasty topper on wet or dry food.",
        },
    },
    {
        id: '10004',
        imgSrc: 'cat_cake_01.jpg',
        imgAlt: 'A cat is watching a cat cake', 
        productDetails: {
            name: 'Cat Ediable Cake',
            category: 'treat',
            price: 28.99,
            review: '5',
            amountOfReviews: '3',
            description: "It's natural for cats to crave flavor and variety in their diet. They’re obligate carnivores, which means they must consume a high protein diet to thrive. That’s why we offer a range of healthy, 100% poultry and seafood treats that are custom formulated to meet the nutritional needs of cats. They’re sure to entice even the most purrsnickety feline. ",
        },
    },
    {
        id: '10005',
        imgSrc: 'cat_bowl_01.jpg',
        imgAlt: 'A cat is eatingn food in a white bowl.', 
        productDetails: {
            name: 'White Ceramic Food Bowl',
            category: 'cat supplies',
            price: 12.99,
            review: '4.9',
            amountOfReviews: '853',
            description: "",
        },
    },
    {
        id: '10006',
        imgSrc: 'cat_bowl_02.jpg',
        imgAlt: 'a cat is eating food in a stainless steel bowl.', 
        productDetails: {
            name: 'Stainless Steel Food Bowl',
            category: 'cat supplies',
            price: 12.99,
            review: '4.9',
            amountOfReviews: '985',
            description: "",
        },
    },
    {
        id: '10007',
        imgSrc: 'cat_bowl_03.jpg',
        imgAlt: 'a cat is eating food in a blue plastic bowl.', 
        productDetails: {
            name: 'Plastic Food Bowl',
            category: 'cat supplies',
            price: 8.99,
            review: '4.8',
            amountOfReviews: '23',
            description: "",
        },
    },

    {
        id: '10008',
        imgSrc: 'cat_bow_tie_01.jpg',
        imgAlt: 'A cat with a yellow bow tie.', 
        productDetails: {
            name: 'Cat Bow Tie',
            category: 'cat wear',
            price: 6.99,
            review: '4.9',
            amountOfReviews: '67',
            description: "",
        },
    },
    {
        id: '10009',
        imgSrc: 'cat_bow_tie_02.jpg',
        imgAlt: 'A cat wears a pink bow tie with a yellow flower.', 
        productDetails: {
            name: 'Cat Bow Tie',
            category: 'cat wear',
            price: 9.99,
            review: '4.5',
            amountOfReviews: '176',
            description: "",
        },
    },
    {
        id: '10010',
        imgSrc: 'cat_costume_01.jpg',
        imgAlt: 'A cat in a hoodie.', 
        productDetails: {
            name: 'Cat Hoodie',
            category: 'cat wear',
            price: 2.99,
            review: '4.9',
            amountOfReviews: '24',
            description: "",
        },
    },
    {
        id: '10011',
        imgSrc: 'cat_costume_02.jpg',
        imgAlt: 'A cat wears clothes and a necklace.', 
        productDetails: {
            name: 'Red Cat Clothes',
            category: 'cat wear',
            price: 6.99,
            review: '4.9',
            amountOfReviews: '53',
            description: "",
        },
    },
    {
        id: '10012',
        imgSrc: 'cat_costume_03.jpg',
        imgAlt: 'A cat wears red clothes to celebrate birthday.', 
        productDetails: {
            name: 'Cat Clothes',
            category: 'cat wear',
            price: 16.99,
            review: '4.9',
            amountOfReviews: '12',
            description: "",
        },
    },
    {
        id: '10013',
        imgSrc: 'cat_triangle_towel_01.jpg',
        imgAlt: 'a cat wears a soft yellow triangle towel', 
        productDetails: {
            name: 'Soft Triangle Towel',
            category: 'cat wear',
            price: 20.99,
            review: '4.9',
            amountOfReviews: '1098',
            description: "",
        },
    },
    {
        id: '10014',
        imgSrc: 'cat_triangle_towel_02.jpg',
        imgAlt: 'A cat wears a blue triangle towel.', 
        productDetails: {
            name: 'Blue Triangle Towel',
            category: 'cat wear',
            price: 12.99,
            review: '4.9',
            amountOfReviews: '928',
            description: "",
        },
    },
    {
        id: '10015',
        imgSrc: 'cat_triangle_towel_03.jpg',
        imgAlt: 'A cat wears a yellow cotton triangle towel.', 
        productDetails: {
            name: 'Cotton Triangle Towel',
            category: 'cat wear',
            price: 18.99,
            review: '4.9',
            amountOfReviews: '1986',
            description: "",
        },
    },
    {
        id: '10016',
        imgSrc: 'cat_glasses_01.jpg',
        imgAlt: 'A cat wears a pair of sunglasses of balck lens.', 
        productDetails: {
            name: 'Cat Sunglasses',
            category: 'cat wear',
            price: 7.99,
            review: '4.9',
            amountOfReviews: '685',
            description: "",
        },
    },
    {
        id: '10017',
        imgSrc: 'cat_glasses_02.jpg',
        imgAlt: 'A cat wears a pair of sunglasses of orange lens.', 
        productDetails: {
            name: 'Cool Sunglasses',
            category: 'cat wear',
            price: 10.99,
            review: '4.9',
            amountOfReviews: '1006',
            description: "",
        },
    },
    {
        id: '10018',
        imgSrc: 'cat_hat_01.jpg',
        imgAlt: 'A cat with a hamburger hat on head.', 
        productDetails: {
            name: 'Hamburger Hat',
            category: 'cat wear',
            price: 12.99,
            review: '4.9',
            amountOfReviews: '956',
            description: "",
        },
    },
    {
        id: '10019',
        imgSrc: 'cat_hat_02.jpg',
        imgAlt: 'A cat wears a red hat on head.', 
        productDetails: {
            name: 'Red hat with rabbit ears',
            category: 'cat wear',
            price: 13.99,
            review: '4.9',
            amountOfReviews: '693',
            description: "",
        },
    },
    {
        id: '10020',
        imgSrc: 'cat_scarf_01.jpg',
        imgAlt: 'A cat wears a warm red scarf.', 
        productDetails: {
            name: 'Beatiful Red Scarf',
            category: 'cat wear',
            price: 16.99,
            review: '4.9',
            amountOfReviews: '291',
            description: "",
        },
    },
    {
        id: '10021',
        imgSrc: 'cat_tree_01.jpg',
        imgAlt: 'A cat is lying on a cat tree.', 
        productDetails: {
            name: 'Three-Level Faux Fur Cat Tree',
            category: 'cat furniture',
            price: 169.99,
            review: '4.9',
            amountOfReviews: '179',
            description: "",
        },
    },
    {
        id: '10022',
        imgSrc: 'cat_tree_02.jpg',
        imgAlt: 'A cat is playing around a cat tree.', 
        productDetails: {
            name: 'Fiber Carpet Kitten Tree',
            category: 'cat furniture',
            price: 69.99,
            review: '4.9',
            amountOfReviews: '540',
            description: "",
        },
    },
    {
        id: '10023',
        imgSrc: 'cat_tree_03.jpg',
        imgAlt: 'A cat is playing around a cat tree.', 
        productDetails: {
            name: 'Real Wood Compact Scratcher',
            category: 'cat furniture',
            price: 89.99,
            review: '4.9',
            amountOfReviews: '629',
            description: "",
        },
    },
    {
        id: '10024',
        imgSrc: 'cat_bed_01.jpg',
        imgAlt: 'A cat is lying in a white soft cat bed.', 
        productDetails: {
            name: 'Utra-Soft Nest Cat Bed',
            category: 'cat furniture',
            price: 56.99,
            review: '4.9',
            amountOfReviews: '496',
            description: "",
        },
    },
    {
        id: '10025',
        imgSrc: 'cat_bed_02.jpg',
        imgAlt: 'A cat is lying in a neat cat bed.', 
        productDetails: {
            name: 'Chill Cat Bed',
            category: 'cat furniture',
            price: 59.99,
            review: '4.9',
            amountOfReviews: '872',
            description: "",
        },
    },
    {
        id: '10026',
        imgSrc: 'cat_bed_03.jpg',
        imgAlt: 'A cat is lying in a soft cat bed.', 
        productDetails: {
            name: 'Cuddle Cloud Cat Bed',
            category: 'cat furniture',
            price: 60,
            review: '4.9',
            amountOfReviews: '793',
            description: "The product line is both pet-centric and pet-friendly. This specially designed cat beds consider the preferences of both cats and their human homeowners, with fabrics that will help your cat regulate body temperature, and blend in smoothly with your furnishings. Only pet-friendly materials, harmless to pets and their pet parents, are used. You can be sure your product is not only well-designed but durable and safely constructed.",
        },
    },
    {
        id: '10027',
        imgSrc: 'cat_tent_01.jpg',
        imgAlt: 'A cat is in the tent.', 
        productDetails: {
            name: 'Cat Tent',
            category: 'cat furniture',
            price: 16.99,
            review: '4.9',
            amountOfReviews: '129',
            description: "",
        },
    },
    {
        id: '10028',
        imgSrc: 'cat_carrier_01.jpg',
        imgAlt: 'A cat in a backpack carrier', 
        productDetails: {
            name: 'Galaxy Cat Backpack Carrier',
            category: 'travel',
            price: 69.99,
            review: '4.7',
            amountOfReviews: '301',
            description: "",
        },
    },
    {
        id: '10029',
        imgSrc: 'cat_carrier_02.jpg',
        imgAlt: 'A cat in a Cotton bag', 
        productDetails: {
            name: 'Cotton Convertible Bag',
            category: 'travel',
            price: 29.99,
            review: '4',
            amountOfReviews: '234',
            description: "",
        },
    },
    {
        id: '10030',
        imgSrc: 'cat_carrier_03.jpg',
        imgAlt: 'A cat in a leather backpack carrier', 
        productDetails: {
            name: 'Convertible Cat Backpack Carrier',
            category: 'travel',
            price: 129.99,
            review: '4.9',
            amountOfReviews: '823',
            description: "",
        },
    },
    {
        id: '10031',
        imgSrc: 'cat_toy_01.jpg',
        imgAlt: 'A cat is playing a fake mice.', 
        productDetails: {
            name: 'Refillable Mouse with Organic Catnip',
            category: 'toy',
            price: 1.99,
            review: '4.1',
            amountOfReviews: '291',
            description: "",
        },
    },
    {
        id: '10032',
        imgSrc: 'cat_teaser_01.jpg',
        imgAlt: 'A cat with a teaser wand.', 
        productDetails: {
            name: 'Cat Teaser Wand',
            category: 'toy',
            price: 5.99,
            review: '4.8',
            amountOfReviews: '2991',
            description: "",
        },
    },
    
];

export default itemList;