import DefaultSubpage from "./DefaultSubpage";

const subpageList =
{
    "Ways to get a cat": {
        title: "Where to get a cat or kitten",
        text: <DefaultSubpage></DefaultSubpage>,
    },

    "Thinking of getting a cat": {
        title: "Thinking of getting a cat?",
        text: (
            <div>
                <p>Having a cat can mean different things to different people. Some want a cat to cuddle and sit on their laps; others are happy to live with a very independent cat which spends most of its time outside and doesn’t want too much human interaction.</p>
                <p>What is important is that you try to find a cat that will interact with you if you want it to. All cats are not the same and how each individual cat behaves with you can depend on its inherent personality and early experiences (or lack of experiences), which can make it fearful or confident with people and life in general.</p>
                <p>The environment in which you keep a cat is also extremely significant – for example if it lives with many other cats which do not get on, then it will be stressed and will react differently than if it was on its own.</p>
                <p>While there is no guaranteed way to choose the perfect cat for you and your lifestyle, understanding your expectations as well as what makes cats tick will help you to bring home a cat that should be able to cope with its new environment and be the pet that you want too.</p>
                <h3 className="article-subtitle">To care for a cat you will need to:</h3>
                <p><ul className="reason-list">
                    <li>Provide plenty of human companionship</li>
                    <li>Provide regular, suitable meals with a constant supply of fresh water</li>
                    <li>Provide a clean and comfortable bed</li>
                    <li>Provide the cat with outdoor access or be prepared to empty and clean a litter tray on a daily basis</li>
                    <li>Provide it with a stimulating and safe environment</li>
                    <li>Groom it regularly. Longhaired cats require daily grooming</li>
                    <li>Have it neutered between 4 and 6 months old</li>
                    <li>Vaccinate against the major feline diseases regularly</li>
                    <li>Worm regularly and provide treatment for fleas</li>
                    <li>Take the cat to the vet when it shows any sign of illness</li>
                    <li>Insure your cat or make sure you can afford the cost of any veterinary treatment it may need</li>
                </ul></p>
            </div>),
    },

    "Choosing a cat": {
        title: "Choosing a Kitten",
        text: <div>
            <p>Think of the different cats you have met in your life. Some have been extra friendly, some nervous or fearful, some bold, some even perhaps aggressive. The cats we come across in our lives can vary from pet cats to community cats to wild living or feral cats. How they have come to be those cats depends on their parents, where they were born, how much handling they have had, and what experiences they had both at an early age and later in life. All of these things can have a profound effect.</p>
            <p>A pet cat could be defined as one that’s happy to be around people and to interact with them – just what most of us want. However, at the other end of the spectrum is the feral cat, an amazing creature which, although it looks exactly the same as a pet cat and is of the same species, can behave very differently – in fact, more like a cat belonging to a wild species (more of this later).</p>
            <p>Cats have a wide range of personalities. How confident or fearful a cat is in adulthood will be affected by what happens in kittenhood. Much of this ‘personality’ development has already taken place before we get our kitten. For the cat, learning to enjoy the company of people takes place pretty early in its life – somewhere from about three weeks to seven or eight weeks old. During this time the kitten hasn’t yet learned to fear everything, and its mind is open to forming bonds with other animals or people and learning how to deal with new experiences without being overwhelmed by them. Think about human children when they’re toddlers, and how fearless they often are – running off without a care, touching and tasting everything, falling over and getting up again. But as they get older they begin to worry and look for reassurance when they do things.</p>
        </div>,
    },

    "What you may need": {
        title: "The Kitten Checklist",
        text: (<div>
            <p>Use this checklist to help you find a healthy, friendly kitten and to avoid some of the pitfalls which can occur</p>
            <p>When you take on a kitten you are taking responsibility for a pet which may be with you for an average of 14 years, and often longer. Most people want a cat which is confident and happy to be around people. How you choose a kitten can have a great effect on both the welfare of the cat throughout its life, and your enjoyment of having it as a pet.</p>
            <p>Whether you pay for a kitten or take on a free one, whether it is a non-pedigree (moggie) or a pedigree, and whether you get it from a charity homing centre, a home fosterer for a cat charity, a private home or a breeder, there are general things to look out for to ensure you bring home a healthy kitten which will live with you happily for many years. The same principles apply no matter where the kitten comes from and they focus on:</p>
            <p>1. Health</p>
            <p>2. Behaviour</p>
            <p>The questions are a guide and prompt you to find out important things which could affect your kitten’s health and wellbeing, and your future relationship with it. Answers suggesting caution may not be a reason to refuse to take a kitten, but it can inform you about what to expect or what you may need to do if you take the kitten home (eg, vaccination, neutering, worming). A brief explanation tells you why finding out these things is important.</p>
            <h3 className="article-subtitle">BEFORE YOU VISIT THE KITTEN</h3>
            <p>1. WHEN WAS THE KITTEN BORN?</p>
            <p>2. WILL YOU BE ABLE TO SEE THE KITTEN WITH ITS MOTHER?</p>
            <p>3. WAS THE KITTEN RAISED WITH ITS MOTHER?</p>
            <p>4. WHERE WAS THE KITTEN BORN, AND WHERE DID THE KITTEN SPEND MOST OF ITS TIME WHEN IT WAS BETWEEN 2 AND 9 WEEKS OLD?</p>
            <p>5. DOES THE KITTEN HAVE BROTHERS OR SISTERS WITH WHICH IT INTERACTS?</p>
            <p>6. IS ANYTHING KNOWN ABOUT THE FATHER OF THE KITTEN?</p>
            <p>7. IS THE KITTEN FRIENDLY?</p>
            <p>8. HAS THE KITTEN INTERACTED POSITIVELY WITH DIFFERENT PEOPLE AND EXPERIENCED SOUNDS, SIGHTS, SMELLS AND SENSATIONS COMMON IN HOUSEHOLDS? (eg. vacuuming, TV/radio, people coming and going)</p>
            <p>9. IS THE KITTEN ON SOLID FOOD?</p>
            <p>10. WAS THE KITTEN TOTALLY OR PARTIALLY HAND-REARED (FED BY A HUMAN USING A BOTTLE)?</p>
            <p>11. IS THE KITTEN HEALTHY?</p>
            <p>12. IS THE KITTEN LIKELY TO BE LONG-HAIRED?</p>
            <p>13. IS THE KITTEN A SPECIFIC BREED?</p>
            <p>14. HAS THE KITTEN BEEN INTERACTING POSITIVELY WITH A DOG OR DOGS?</p>
        </div>),
    },

    "Making introduction": {
        title: "Making introduction",
        text: (
            <div>
                <p>It’s one thing to establish a harmonious household when there are only adults and cats co-habitating. It’s quite another when you add both dogs and children to that domestic stew. Finding harmony in a “multi-species” home can offer a variety of challenges, so let’s take a look at a few basic steps you can take to keep that harmony train on the track.</p>
                <p>As discussed, Catification is all about optimizing your home environment for both you and your cat, and ensuring that your cat’s territorial security is taken care of. This will be absolutely foundational in our process here, because if your cat can’t feel secure in the home terrain, this will be a constant source of friction moving forward.</p>
                <h3 className="article-subtitle">Your basic Catification checklist would include:</h3>
                <p>Establish a Vertical Terrain: Your cat is the only non-terrestrial being in your house. You can use this to your advantage by offering them multi-level environments (as best described in my “Cat Superhighway” concept). This essentially maximizes the real estate of your home and expands the available living space for all family members.</p>
                <p>Signposts and Scent Soakers: Signposts are objects that signify territorial ownership for your cat, and scent soakers are soft items that absorb a cat’s scent. For optimal territorial security, make sure your cat has ample signposts/scent soakers, like scratching posts, litter boxes, towels, blankets, and cat beds.</p>
                <p>Cat TV: Create a window destination location with a cat tree, perch, or cat bed that invites your cat to sit and observe the outdoor happenings. This will serve as a valuable activity/distraction for your cat, which indirectly benefits all family members.</p>
                <p>Urban Planning: This is a process for setting up your home to accommodate the needs of everyone who lives there— humans and animals —in a way that promotes peaceful coexistence. The key is traffic flow: everyone must be able to move freely through the space without conflict. For cats, this means eliminating any dead ends or ambush zones, where a cat might be “forced” into an unwanted encounter with a child or a dog.</p>
                <p>Speaking of “unwanted encounters,” it is paramount that your dog can perform a down-stay, on command, without fail. Otherwise, you risk setting up a toxic relationship with your dog and cat from day one, and this isn’t fair for either one of them.</p>
            </div>),
    },

    "Every day care": {
        title: "Everyday Care for your Cat",
        text: (
            <div>
                <p>The level of general care you will need to give your cat will depend on its breed or length of fur (or lack of it), its health and its age. Below are are the key things you need to think about.</p>
                <h3 className="article-subtitle">Caring for your cat’s coat and skin</h3>
                <p>There is not a great deal to do with short-haired breeds as they can keep their coats in tip-top condition with little or no help. There is more work to be done with long-haired breeds and a great deal with Persians which have a very thick undercoat as well as a long top layer of hair. They may have problems grooming because of the shape of the skull and jaw caused by breeding for a very flat face.</p>
                <p>Keep the area under the tail clean (only really a worry in breeds with a great deal of coat such as Persians, or cats that are unwell and have diarrhoea). You may need to clean or trim the coat so faeces do not stick to it. Help may also be needed for older cats which are not so supple and cannot clean themselves.</p>
                <p>There are some breeds which have little or no hair. While this may seem to be a way to remove the need for any type of grooming, it actually adds problems in terms of care of the skin. The cat species has developed to have hair because it has a range of roles in the cat’s survival – warmth, protection of the skin, as a sensory mechanism with highly sensitive hairs, as a way to distribute oil to keep the coat waterproof and to hold scents. To keep this coat in tip-top condition the cat has developed a highly effective grooming mechanism – a tongue which is very rough with small barbs on the surface so that it works like a comb. Grooming also seems to make cats feel good – they will often groom after having a surprise or use it as a distraction. Therefore to breed a cat with no coat, but with a desire to groom and a very rough tongue seems rather unfair.</p>
                <p>Breeds with no or little coat may be prone to skin problems including the development of rashes and fungal infections. Owners must pay meticulous attention to keeping the skin clean and supple. The skin needs to be bathed or sponged every week to remove its oily secretions.</p>
                <h3 className="article-subtitle">Caring for your cat’s eyes</h3>
                <p>Most cats do not need any help with their eyes – everything is kept clean with regular grooming. However, the very flat-faced breeds such as Persians and Exotics have been bred with skulls which are not the normal cat conformation. Often the tear ducts (which let the tears which lubricate the eye drain away without anyone noticing) have had their path blocked by changes to the shape of the skull. The result is that the tears overflow down the face causing staining and probably discomfort for the cat. The dampness can cause skin problems too.</p>
                <p>Gently wipe with a cotton wool ball dampened with clean water or a little baby oil. Use a separate ball for each eye and dry with a soft tissue. Do not touch the eyeball as this will be painful and the cat will try to avoid the experience next time.</p>
                <h3 className="article-subtitle">Caring for your cat’s claws</h3>
                <p>Most cats which are active and go outside care for their own claws without the need for help – they keep them clean and sharp during their activities. Indoor only cats may need their claws trimmed (principally to protect the furniture) as they may not wear them down in the same way. They will certainly need somewhere to scratch.</p>
                <p>Old cats may not retract their claws so well and they may begin to catch on carpets or furnishings. Keep an eye on these so that they do not become overgrown or begin to curve back into the cat’s pad.</p>
            </div>),
    },

    "Caring for the elderly cat": {
        title: "Elderly cats – special considerations",
        text: (
            <div>
                <p>Cats are living much longer now than was the case 20 years ago, thanks to better nutrition, veterinary and home care. In recent years, feline ages and life-stages have been redefined, cats are considered to be elderly once they reach 11 years with senior cats defined as those aged between 11-14 years and super-senior cats 15 years and upwards. When caring for older cats it sometimes helps to appreciate their age in human terms.</p>
                <h3 className="article-subtitle">The effects of ageing</h3>
                <p>With increasing age, there are many changes to a cat’s physiology, behaviour and vulnerability to particular illnesses. Physiological changes include reduced ability to smell and taste food, reduced ability to digest fat and protein, reduced hearing, immune function, skin elasticity and stress tolerance.</p>
                <h3 className="article-subtitle">Behavioural changes</h3>
                <p>As cats age, their behaviour alters too, often as a direct result of the physiological changes taking place. The elderly cat adapts gradually to these changes and it may not be apparent unless you are specifically looking for signs of ageing. Older cats hunt less, spend less time outside, are generally less active and sleep for longer periods. They can have a reduced or fussy appetite, be less keen to play or groom and be more vocal. They also tend to become more insecure and therefore potentially more dependent on you.</p>
                <p>Other behavioural changes can be seen as a direct result of disease, for example, increased thirst or appetite or aggression associated with pain.</p>
                <h3 className="article-subtitle">Home care for the elderly</h3>
                <p>This is the time, more than any other, when your cat needs some essential care. As cats get older they will find it more difficult to maintain their own cleanliness and checking your cat regularly will enable you to detect problems that need to be tackled straight away.</p>
                <h3 className="article-subtitle">Grooming</h3>
                <p>Your old cat is less able to groom efficiently so you may need to wipe away any discharge around its eyes, nose or anus using separate pieces of cotton wool for each area moistened in warm water. You may also need to brush your cat using a soft brush and fine comb but care should be taken to ensure you are gentle, as older cats tend to be thin with very little padding over their bones so vigorous combing can be painful. At this time you can also check for lumps, bumps, sores or anything else that merits attention from the vet. Grooming shorthaired cats only needs to be completed thoroughly if there is any matting. This can often occur on the lower spine and hindquarters as your cat may be less flexible and therefore unable to reach these areas to self-groom.</p>
                <p>If your cat is longhaired and is having difficulties keeping itself clean it may be helpful to trim the coat around its anus, underside of the tail and back legs to avoid soiling or matting. If you find any matts then they should be teased out rather than cut with scissors as this can so easily damage the skin. If you have any concerns, consult your veterinarian as severe matts can be very uncomfortable for your cat.</p>
            </div>),
    },

    "Preventative healthcare": {
        title: "Keeping your Cat Healthy",
        text: (
            <div>
                <p>Anyone who’s familiar with the behaviour of the cat will know that the saying ‘a cat is not a small dog’ is indeed very true – the same is true for health – you can’t just take the diagnoses and treatments applicable to dogs and scale them down to a cat.</p>
                <p>The cat has its own unique physiology, diseases and reactions to drugs and treatments. Cats also have their own set of behaviours that can make even noticing illness very difficult. Cats never make things straightforward, which is probably why so many of us are fascinated by them – you need to be a good detective to work out a cat! So what are the extra hurdles which cats present when it comes to their health?</p>
                <h3 className="article-subtitle">Keep up your preventative care</h3>
                <p>Just like in human health, good nutrition, keeping a healthy weight and taking exercise are important for cats. Also keeping them free of parasites such as fleas, worms and ticks is important, as is appropriate vaccination (discuss this with your vet). </p>
                <h3 className="article-subtitle">Cats can look remarkably well even when there are problems</h3>
                <p>It’s remarkably difficult to age a cat just by looking at it. In its first year or even its second, the cat has a youthful look and energy that give us some clues. However, after that many of our cats can seem to remain unchanged into their mid-teens if they’re lucky. As they get into double figures many dogs go grey around the muzzle and face, move less easily and change their body shape – it’s fairly obvious that they’re ageing. But the youthful-looking cat doesn’t go grey and could easily fool you as to its actual years. If it looks old it’s probably very old.</p>
                <h3 className="article-subtitle">Cats are masters of disguise when it comes to showing pain and vulnerability</h3>
                <p>Cats are predators and as such we think of them always at the killing end of a predator/prey encounter and always on top. However, the cat is a small predator, and there are other animals (and even people) who’d be happy to treat it as prey as well. The cat, of course, is well aware of this. It doesn’t have a pack to hide within like a dog, no others of its kind that are going to stand up for it or provide a united front against a threat. It’s a small animal with only itself to rely on when it comes to avoiding or escaping from a dangerous situation. Therefore it needs to ensure that it doesn’t show vulnerability or weakness that might draw an opportunistic predator’s attention.</p>
                <p>Probably because of this, cats are excellent at not showing they’re ill. They don’t whine like the dog. They often just become quiet and stoic, and unless you notice that this is, in fact, a change in their normal behaviour you may not take a second glance – the cat removes itself from the radar and merges into the background until it feels better.</p>
                <h3 className="article-subtitle">Owners have to be detectives when it comes to noticing behaviour changes</h3>
                <p>Cats often just go quiet when they’re ill, and in a busy household where the cat uses the garden rather than a litter tray as its toilet, there may be no obvious signs that it is unwell. It may be one of those cats that drinks outside because it prefers rainwater to water in a dish, so owners may not even notice an increase in thirst and drinking. Without a litter tray owners may not notice diarrhoea or a change in the volume of urine, and so not pick up these pointers to a problem. If the cat has simply gone quiet or seems to sleep more nobody may ask any questions. If it’s less interactive or a bit grumpy it takes an owner who can let this clue enter his or her consciousness in a busy life to realise that it might mean something.</p>
            </div>),
    },

    "Get neutered": {
        title: "Neutering your cat",
        text: (
            <div>
                <p>From around the age of 4 months, kittens reach sexual maturity and are therefore capable of breeding and producing kittens themselves. Most people do not have the time or desire to breed from their cat and do not wish to add to the number of unwanted cats and kittens already looking for homes. Neutering a cat – castration in the male (removal of the testes), and spaying the female (removal of the ovaries and uterus) – not only prevents unwanted pregnancies occurring but also curbs unwanted behavioural patterns associated with sexual maturity and reduces the risk of certain diseases.</p>

                <h3 className="article-subtitle">Reasons for neutering female cats</h3>
                <p>1. Population control. It is important to neuter a female cat before she can have kittens herself. This happens very quickly depending on breed, time of year born and individual development. The first season usually occurs around six months but can be earlier. Queens can have up to three litters in a year.</p>
                <p>2. Control of nuisance. Female cats will ‘call’ (come into season and be receptive to the male cat) regularly, about every three weeks during sexually active times of the year if they do not get pregnant. Having entire female cats in an area will attract entire males with the attendant problems of spraying, fighting and caterwauling.</p>
                <p>3. Welfare issues. Unwanted kittens may not be cared for and are likely to suffer from various infectious diseases such as cat ‘flu or worse. There are unlikely to be enough new homes available for them.</p>
                <p>4. Health issues. Female cats which are not neutered are more likely to suffer from pyometra (infection of the womb) later in life and with mammary tumours. Queens with infectious diseases may pass these on to their kittens. Pregnancy and birth are also not without risk.</p>
                <p>5. Wildlife issues. Cats with kittens will hunt more actively and if they are not being fed will need to catch more wildlife to feed their kittens.</p>
                <h3 className="article-subtitle">Reasons for neutering male cats</h3>
                <p>1. Control of nuisance. Unneutered male cats are likely to stray over a large area, will mark their territory with a very pungent spray and are much more likely to fight – with attendant noise nuisance.</p>
                <p>2. Health issues. Fighting males are much more likely to spread diseases such as FIV and FeLV to other cats. They are also likely to suffer from fight injuries such as abscesses. Because they wander over a large area they are also at greater risk of suffering road traffic accidents.</p>
                <p>3. Pet issues. Unneutered male cats will wander from home and may not return. They may also spray inside the home and may be aggressive to their owners. Therefore it is desirable to neuter kittens early enough to ensure that the above problems are prevented. Most people do not want to live with an unneutered male cat.</p>
                <p>4. Population control. Obviously, male cats do not have kittens themselves and it only takes one male in an area to make lots of female cats pregnant, so neutering a female cat makes a great deal more difference to limiting numbers, but it all helps!</p>
            </div>),
    },

    "Seasonal hazards": {
        title: "Seasonal hazards",
        text: (<div>
            <h3 className="article-subtitle">Christmas safety for your cat</h3>
            <p>Most of us look forward to the festive period; the food, the guests, the tree and decorations. However, for cats, Christmas may be a time of stress and risk of injury. As a species they enjoy routine and are sensitive to changes in their environment, making the celebrations challenging. In addition, the season means certain toxic plants and food may be accessible to curious cats. At International Cat Care we have consulted our veterinary members to ask them what injuries they see at this time of year. Based on this information and with the input of the Veterinary Poisons Information Service (VPIS) this article offers advice on what to keep out of reach and what to do to minimise the disruption to keep our cats happy this Christmas.</p>
            <p>Poinsettia is often mentioned as a potentially poisonous plant but its reputation is perhaps unfair. The Veterinary Poisons Information Service informs us that in over half the cases of pets eating Poinsettia plants reported to them, the cat or dog shows no signs of illness. If they do show any signs they are mild such as being sick, drooling, refusing food and being quieter than normal. Even these signs soon resolve without any specific treatment. Nevertheless, it is still a good idea to keep the plant out of reach. In addition, mistletoe, holly, ivy and Christmas cherry can cause a tummy upset and should be kept away from inquisitive cats.</p>
            <p>Many cat owners have had the experience of their cat climbing the Christmas tree and it falling over. Usually, both are unharmed but it is worth considering securing the tree to avoid this. Injuries are reported from falling from Christmas trees and from the resulting smashed baubles, with glass ones particularly sharp when broken. Ingestion of Christmas tree needles and the fake snow applied to them can cause stomach upset and other decorations can be ingested resulting in a ‘foreign body’. Chewing of lights and wires can be a problem, especially for nosy kittens and it is not uncommon for cats to pass urine just where you don’t want them to i.e. the tree, potentially a problem if electric plugs and wires are exposed.  This can be a sign of stress so read on for techniques to reduce the anxiety cats may suffer at this time of year.</p>
            <p>One of our vets reported seeing a cat with a singed tail from Hanukkah menorah candles and certainly exposed candles can be a hazard to cats who tend to jump onto window sills and mantelpieces where candles are placed. As elevated locations are still accessible to most cats, candles should be kept where you can keep an eye on them or left off the Christmas list.</p>
            <p>At this time of celebration food may be left out, left-overs left within reach. We traditionally worry about dogs and chocolate toxicity for example but what about cats? Chocolate is also toxic to cats, although the amount a cat needs to eat to make them ill is a lot higher than for dogs. Signs of chocolate poisoning including being sick and passing diarrhoea, drinking a lot, appearing drunk, trembling or even having a fit. Hopefully, a cat’s lesser interest in sweet treats means this risk is small.</p>
            <p>Similarly, grapes and raisins, known for causing kidney damage in dogs, may affect cats but poisoning is much less common. The VPIS would, however, advise treatment of cats known to have eaten these foods, and suggest that for example mince pies are not left out. If you think your cat has eaten such food contact your vet and encourage them to call the VPIS for advice. On the subject of food, it may be tempting to treat your cat this Christmas, perhaps extra cat treats or some scraps from the Christmas dinner. While a little left-over turkey will be enjoyed by the majority of cats without harm, excessive treats and human food could make a cat poorly so do try and stick to their normal feeding routine this time of year; they won’t know they are missing out! Another hazard can be cooked poultry bones – they are hard for cats to digest and can get stuck in the digestive system so make sure your cats can’t raid the bin after the Christmas lunch.</p>
            <h3 className="article-subtitle">Halloween Hazards and Fireworks</h3>
            <p>In October and November celebrations for Halloween and Bonfire Night (in the UK) take place, not just on one or two evenings, but over several weeks it seems; indeed similar celebrations now also happen at New Year. Although great fun for us humans, our cats may find them both stressful and dangerous.</p>
            <p>For us, fireworks are bright, noisy and enjoyable to watch, but for a cat they may be a new experience (and therefore make the cat wary), loud and unpredictable, and can be very frightening. Frightened cats may be startled, run away and become lost, or run across roads and be involved in accidents. Distressed cats can develop behavioural issues such as house-soiling or excessive grooming.</p>
            <p>Shutting your cat inside if it is not used to being restricted or called in. Some cats are not used being restricted indoors or using an indoor litter tray. If this is the case, ‘rehearse’ confinement overnight in the run-up to the event.Practise getting your cat to come to you when called. When your cat is hungry, call his name and reward approach with a tasty treat (you can do this first when the cat is indoors). If your cat is not very food motivated, you can reward it coming to you with a game it enjoys, such as with a wand toy. Once your cat has mastered coming to you when called within the home, you can extend this to the outdoors. Always be ready to reward your cat with food or play so that it learns that coming home from outdoors is rewarding. In this way, your cat will continue to be motivated to come to you.Coming indoors at night may be safer for your cat longer term, as night time is when more road accidents and cat fights occur.</p>
        </div>),
    },

    "Going outdoors": {
        title: "Letting your cat/kitten outside for the first time",
        text: (<div>
            <p>Before allowing your new kitten or cat outside, ensure it has a means of identification, either a securely fitted collar with a tag (showing your telephone number) or, ideally, a microchip identification implanted under the skin on the scruff of the neck.</p>
            <p>Prior to any trips outside it is worth considering how you intend to give your cat or kitten access outdoors in the long-term. If you are at home for large periods of the day you may wish to consider allowing access ‘on demand’ via the back door or a conveniently positioned window, for example. However, if you are out at work during the day you may prefer to install a cat flap. The local environment will dictate what rules you put in place regarding any time limits on access outside. You may wish to confine your kitten or cat at twilight so that it can remain indoors at night, or limit its access outside at times when traffic may be busy locally.</p>
            <p>Because of potential infection with diseases such as enteritis or cat flu, your kitten should not be allowed outside until at least a week after it has finished its first course of vaccinations at about 13-14 weeks old (depending on the vaccine). You could then let it explore outside if it is supervised. Once it is fully vaccinated and has become used to living in your house, you can start to let your kitten go outside a bit more. However, before you allow your kitten free access outdoors, make sure it has been neutered (at around 4 months). You should also ensure your garden is safe for your kitten first by covering any ponds, blocking up any holes in the fencing and removing any potentially hazardous garden substances or objects, such as wood preservatives, insecticides, sharp implements etc.</p>
            <p>It’s useful to get your kitten or cat used to being called to come to you – you can do this by offering it little treats so that it’s happy to respond. You then have a little bit of control when you go outside to call them in.</p>
            <p>Choose a dry day (if possible) and a quiet time when you can accompany your kitten outside, allowing it to explore the new environment. Excitements, such as other cats, dogs which might bark or children screaming in the neighbour’s garden, are best avoided for the first couple of excursions so that your kitten (or cat) can concentrate on you and isn’t spooked. Continue to accompany your kitten until it is used to your garden and can find its way back to the house without difficulty. It is best not to leave your kitten outside alone until it is 6 months old and it is essential that it is neutered (from 4 months of age) before allowing it unsupervised access.</p>
            <p>If you have adopted an adult cat you probably will have been advised to keep it in for 2-3 weeks to settle into its new home. Some cats will tolerate this period well yet others will look to go outside sooner rather than later. It is probably best to stick to this timescale, particularly if you feel there have been any signs of anxiety since its arrival. When you first decide to allow your cat outside, choose a quiet, dry period when you are at home all day and do so a short while before a routine mealtime. Accompany your cat outside but don’t be alarmed if it disappears into some shrubbery; this is a normal strategy to enable it to get acclimatised to its new environment in a place where it can observe without being seen. Leave the back door open initially and, after 30-60 minutes, call your cat indoors for its meal and then repeat the following day. Most cats adapt extremely quickly to exploring their new territory outside and they probably will not need a gradual introduction of this kind but the more timid individuals may benefit from gradually increasing periods outside in the first few weeks.</p>
            <p>Some people take on adult cats that have never been outside before and wonder if they’ll be able to adapt to going out into the big wide world. But it’s amazing how adaptable cats are, and there are many examples of cats that have led an indoor existence for most of their lives relishing the opportunity to go outside in a new environment. They may be a little nervous at first, but most take to it like a duck to water. Some even do some hunting and it’s fascinating to think that all of this instinctive behaviour has lain dormant yet can still spring to life when the cat gets the opportunity to do what comes naturally!</p>
        </div>),
    },

    "Lost and found": {
        title: "Lost your cat?",
        text: (<div>
            <p>We understand how distressing it is when a cat goes missing. Do not lose hope; cats have been known to return safely home after several weeks, months and even years. Follow this advice to help improve your chances of being reunited.</p>
            <h3 className="article-subtitle"></h3>
            <p>Social media is a powerful tool to help find lost cats. Use Facebook and Twitter to post a picture of the cat, a description, where and when it was last seen, and your telephone number. Ask as many people as possible to share/retweet the post. Post on the pages of local and national rescue and rehoming organisations too – if anyone finds your cat they may get in touch with these organisations. Many places have a local Facebook page, where people post things relevant to the area; post on these pages too.</p>
            <p>Speak to people in the local area, such as neighbours and staff in local shops and pubs, to find out if anyone has found a cat.</p>
            <p>Ask neighbours and people in the local area to check their sheds, garages, cars, cellars, cupboards etc. It may be that your cat found somewhere nice to sleep but became shut in. If the cat is injured, he or she could be hiding in a hedge or shrub etc – ask neighbours to check their gardens too.</p>
            <p>Check within your own property, including the garden and any outbuildings eg, garage, shed, that your cat is not hiding or has not become trapped in anywhere or that it is hiding.</p>
            <p>Phone around local rescue/rehoming centres and veterinary practices. A lost cat may be handed into these places</p>
            <p>Put posters up in the local area, with a picture of the cat, description, where and when it was last seen, and your contact telephone number. Ask to place these on local notice boards and in shops and pubs to increase your reach. You could also deliver these to surrounding households.</p>
            <p>Try calling your cat at night when it is quiet and so they have more chance of hearing you and you have more chance of hearing them responding. Walk around the neighbourhood calling them.</p>
        </div>),
    },

    "Poisons": {
        title: "Poisonous plants",
        text: (<div>
            <p>Most of us are surrounded by plants, both wild and cultivated, in our homes and gardens and come to no harm. However, a small percentage of these plants have the potential to cause harm to ourselves and our cats.</p>
            <h3 className="article-subtitle">What are the risks?</h3>
            <p>Most cats are fastidious creatures and are careful about what they eat. Poisoning in cats is therefore generally rare. It is the young inquisitive cat or kitten that is most at risk of eating harmful plants, particularly household ones. Boredom also has a part to play. When a cat is confined to a run or lives entirely indoors, hazardous plants should be removed from its environment. Cats given free access to the outside world tend to have other things to occupy their minds than sampling unfamiliar vegetation. But even free-roaming adult cats may accidentally ingest needles or seeds that have become entangled in their coat during grooming.</p>
            <p>All plants, even grass, can have an irritating effect on a cat’s gastrointestinal system causing it to vomit. But, given the opportunity, cats like to nibble on grass. When not available, their attention may turn to less suitable household plants. Particularly dangerous are Dieffenbachia (Dumb Cane), and lilies, which are popular in bouquets and flower arrangements.</p>
            <h3 className="article-subtitle">Preventive action</h3>
            <p>Remove all potentially hazardous household plants to prevent unnecessary exposure. This is especially important for kittens and for cats kept indoors. A list of plants that are unsuitable for a house with cats is given below.</p>
            <p>Outdoors the story is not so simple. Free-roaming cats have access to many gardens so it will be impossible to prevent all possible contact with potentially harmful plants. You can, however, remove the most toxic plants from your garden and make a note of any in your neighbours’ gardens that are potentially dangerous. List common and Latin names. This list may help your vet if poisoning is suspected.</p>
            <p>You can also ensure that any new additions to the garden are safe. The Horticultural Trade Association has a code of practice for its members, and most garden centres and nurseries label plants that are toxic or cause skin reactions. Plants are grouped into three categories:</p>
            <p>A – Poisonous</p>
            <p>B – Toxic if eaten</p>
            <p>C – Harmful if eaten</p>
            <p>You are unlikely to find a category A plant on sale – Poison Ivy being one example. Category B plants should be avoided.</p>
            <p>After gardening, never leave hedge clippings or uprooted plants near pets. Their novelty value may encourage inquisitive chewing. Sap from damaged stems can cause skin irritation as well as being poisonous. Bulbs, rhizomes and roots can be the most hazardous parts of some plants.</p>
        </div>),
    },

    "Cats and your family": {
        title: "Some important zoonotic diseases",
        text: (<div>
            <p>Diseases which can pass between animals and people are called zoonoses and there are some which are transmissible from cats to man (and vice versa). Although these hazards are few, you need to take precautions and be aware that there can be a problem.</p>
            <p>Fortunately, most feline zoonotic diseases are rare, although many myths exist regarding disease risks, and misinformation is often spread through ignorance or fear. In reality, many more people become sick each year from food-borne illnesses than ever fall ill from contact with cats. Practising common sense together with a good hygiene routine, including careful handling of litter trays and routine treatment of cats for fleas and other parasites, significantly reduces the possibility of disease transmission from cats to humans.</p>
            <h3 className="article-subtitle">Cat bites</h3>
            <p>Bacteria in the mouths of cats and, in particular, Pasteurella multocida, can cause infection of a bite wound and result in painful swelling and even abscessation. Bite wounds should be washed carefully and immediate advice sought if swelling, pain or obvious infection occurs. Routine protection against tetanus is also an important consideration and advice should be sought from your doctor.</p>
            <h3 className="article-subtitle">Fleas</h3>
            <p>Fleas are extremely common on cats and although most cat fleas cannot actually live on humans, they can bite humans and cause skin irritation. Fleas should be controlled by regular cleaning and spraying of the environment with a flea-control preparation in addition to regular treatment of all cats for fleas.</p>
            <h3 className="article-subtitle">Ringworm</h3>
            <p>Ringworm (dermatophytosis) is one of the most common zoonotic diseases derived from cats. Cats should always be checked for suspicious lesions, and gloves worn if ringworm is suspected. Your veterinary surgeon can help in screening and identifying cats with suspected ringworm, and in treating any confirmed cases. It is important not to let children have direct contact with ringworm-infected cats, and careful hygiene precautions are necessary when handling such cats (disposable gloves and protective clothing). Attention must also be paid to environmental hygiene as ringworm spores are resistant and can be shed into the environment in high numbers. If any skin lesions occur after contact with cats, immediate medical advice should be sought.</p>
            <h3 className="article-subtitle">Toxoplasma</h3>
            <p>Toxoplasma is a parasite that infects cats and many other mammals, including humans. It is primarily a concern for pregnant women as, if infection occurs during pregnancy, damage can occur to the developing foetus. Most human infections come from poor meat hygiene (handling uncooked meat, eating undercooked meat). However, for a short period, after they are first infected, cats may shed eggs (oocysts) in their faeces, and this is another potential source of infection for humans. Because of this, it is recommended that litter trays should always be emptied and disinfected on a daily basis (the eggs don’t become infectious for humans until more than 24 hours after they are shed in the faeces) and that pregnant women are not involved in cleaning litter trays.</p>
            <h3 className="article-subtitle">Intestinal worms</h3>
            <p>Very rarely, humans can become infected with a cat roundworm (Toxocara cati) or the tapeworm (Dipylidium caninum). These infections are very uncommon (canine roundworm infections are more common in people), but regular worming of cats for both roundworms and tapeworms is an important part of the healthcare of cats.</p>
            <h3 className="article-subtitle">Campylobacter and salmonella</h3>
            <p>These are two intestinal bacteria that can be a cause of severe gastrointestinal disturbances and can affect many animals, including humans. Infection in humans is usually through the food chain and infection from cats is rare, although they can be a potential source. Everyday hygiene precautions (eg, washing hands after handling a cat) should always be followed, but particular care should be paid to handling cats with diarrhoea. If the diarrhoea is prolonged, severe, or contains blood, veterinary attention should be sought to identify the underlying cause. If campylobacter or salmonella is identified, specific treatment and monitoring may be required.</p>
            <h3 className="article-subtitle">Cat scratch disease</h3>
            <p>Cat scratch disease (CSD) is a rare condition characterised by swollen lymph nodes and sometimes other signs (eg, fatigue, muscle pain, sore throat) that can occur following contact (eg, being bitten or scratched) with a cat. CSD is an uncommon disease and serious illness is very rare. The main organism responsible for this disease (Bartonella henselae) appears to be quite common in cats, but transmission to humans is very inefficient. Transmission of this organism between cats appears to occur mainly via fleas</p>
        </div>),
    },

    "Home environment": {
        title: "Making your Home Cat Friendly",
        text: (<div>
            <p>Your cat’s happiness is greatly influenced by how you behave and what kind of lifestyle you offer – as the cat is a territorial species, the environment is everything! First of all, therefore, you need to get the cat-related equipment and facilities right, particularly if you keep your cat exclusively indoors or give it restricted access outside. Even if you haven’t made the decision to have a housebound cat, you may have to confine yours indoors due to ill health or have one that chooses to only go out occasionally because it is nervous or getting old. Having said all that, there is no reason why the following suggestions for a cat friendly home shouldn’t apply to all pet cats, even those with free access to outdoors!</p>
            <p>Your cat’s ability to choose, based on personal likes and dislikes, is compromised when you are in sole charge of making the decisions, such as where your cat feeds or where it goes to the toilet. If you base those decisions on purely human considerations (or what you perceive to be important to your cat) then you could be making the cat’s life a little less than perfect.</p>
            <h3 className="article-subtitle">Try to satisfy specific needs</h3>
            <p>As cats have such specific needs it isn’t enough just to provide some food, shelter and love. While these elements are as important as ever to your cat, it is the quality and quantity of each that is the key. There are practical challenges about the provisions you make for your cat in the home: What sort of cat bed should you provide? Where should you locate the scratching posts? What sort of litter facilities would your cat want?</p>
            <p>A cat friendly home takes into consideration the needs of the cat as a very different species to man. It provides an environment that is safe and stimulating.</p>
            <p>Most homes are not necessarily the ideal habitat for a domestic cat, so provisions have to be made to cater for their specific needs. You may have heard the phrase ‘environmental enrichment’ with regard to keeping a cat happy indoors. This basically means making provisions within a cat’s confined environment that stimulate and challenge and enable it to perform natural behaviour. Living indoors almost automatically deprives a cat of the ability to behave naturally and experience the challenge and frustration that occurs in an outdoor lifestyle. Indoor cats will adapt to their environment but can fall victim to a number of physical or emotional problems associated with boredom and lack of activity. In the absence of the challenge of hunting, exploring and social contact, cats will fill the void of activity with those that are readily available such as sleeping, grooming and eating. It is no coincidence that indoor cats develop physical problems associated with a sedentary lifestyle, for example, urinary tract disease, over-grooming problems and eating disorders.</p>
            <h3 className="article-subtitle">A cat friendly home</h3>
            <p>A cat-friendly home is about compromises that you can make so that the environment suits you both. However, if you are a lover of contemporary minimalistic interiors you are probably going to have to adjust more than most to provide everything your cat needs. Open-plan living spaces with clean lines and an overall lack of clutter may be the basis of the modern style, but this couldn’t be further removed from your cat’s natural habitat. Although the domestic cat is highly adaptable to most landscapes, it still requires a degree of camouflage to enable it to roam relatively inconspicuously. This camouflage can be found almost anywhere apart from the contemporary living space; it is very hard to disguise a cat in an empty room! The slightly more cluttered home is a haven of possibilities for a cat, offering high places to sit and plenty of places to disappear from view.</p>
            <h3 className="article-subtitle">Keeping safe</h3>
            <p>While it is essential to stimulate and challenge cats within the home there is also a duty of care to keep them safe. There are many household appliances, features and products that could be potentially dangerous. It is important therefore to ‘risk assess’ the home on a regular basis to keep these dangers to a minimum. There is a happy medium however between overwhelming anxiety about all possible risks and a casual laxity. An owner’s constant concern for the wellbeing and safety of his or her cat can cause it to develop a sense of helplessness and inability to function normally without the owner present. Equally, an irresponsible attitude to safety by the owner could lead to a tragic accident.</p>
        </div>),
    },

    "Cat Communication": {
        title: "Cat Communication",
        text: (<div>
            <p>Cats communicate in a variety of different ways, and to properly understand cats it is vital to appreciate how and why they communicate. In the preliminary stages of aggressive or combative behaviours, cats will tend to avoid looking at each other directly. Indeed looking directly at a cat may be interpreted as challenging/aggressive by the cat, which may be one reason cats often seem to choose people to sit on that are relatively disinterested in them!</p>
            <h3 className="article-subtitle">Visual signalling</h3>
            <p>Visual signals are important for communicating mood and intentions. Body postures, expressions, pupil size, and their ability to erect hairs on some or all of the body, are all involved in visual signalling. However, compared to wolves and dogs, cats have relatively immobile and flat faces which somewhat limits facial expressions.</p>
            <p>The tail position is one of the well-characterised means of visual communication – generally the ‘tail up’ position with the tail held vertically in the air, perpendicular to the ground is signalling friendly intent when the cat approaches another cat, animal or human – ears are normally pricked up and whiskers are relaxed. Other tail positions and movements will communicate other moods or intentions – a tail held out, slowly moving from side to side across the body may indicate aggression, and in more extreme cases the tail may be held up and ‘puffed out’ by raising the hairs (piloerection) to make the tail and cat appear bigger – this is usually continued as a strip along the spine as well. The tail is tucked between the back legs often signals nervousness and/or submission.</p>
            <p>Visual signals are not limited to tail position – facial expressions are very important too, in particular alterations in position or movement of the eyes, ears, and mouth; and whole body posture is also significant. Erect ears and holding them rotated out along with narrow/small pupils usually signals anger and aggression, whereas pupil dilation and ears being held down against the head usually signals fear. A relaxed cat will usually have its ears facing forward in the normal position.</p>
            <p>An arched back may indicate the cat is in a defensive mode, and a cat crouching down ‘cringing’, often with the tail thumping on the ground is classic defensive posture. A stretched body may indicate either confidence or, in some cases, aggression with a readiness to attack.</p>
            <p>Eye contact can also be important – staring, with little blinking is a challenge, while relaxed eye contact with blinking and winking, sometimes with half-closed eyes is non-threatening and indicates contentment. Also when tense or highly alert the whiskers will be fanned out and point forward in front of the face, whereas when the cat is relaxed the whiskers point directly out and are less spread. A frightened/nervous cat may flatten the whiskers against the side of the face and bunch them together.</p>
            <p>A variety of other visual communication signals are recognised in cats, but not all are well understood. It has been postulated that scratching behaviour (scratching repeatedly on a vertical surface for example) may in part be a visual signal, perhaps involved in some way in territorial marking. However, scratching areas tend to be within the routes most commonly used inside a cats ‘home territory’ and do not appear to be used to mark out the periphery. Many cats will also roll at times – rolling on their backs and exposing their abdomen. Again, this is not well understood, but it has been suggested that this may be a friendly/submissive posture.</p>
            <h3 className="article-subtitle">Tactile communication</h3>
            <p>Common forms of tactile (touch) communication include allorubbing (two cats rubbing their bodies against each other – this especially occurs around the mouth/cheek area, but also along the body and tail regions), allogrooming (two cats grooming each other), nose touching, and resting/curling up together. Cats using each other as ‘pillows’ is a behaviour that is seen both in domestic and feral cats, as is cats backing up against each other and intertwining their tails. This is assumed to be a form of social bonding, but as with much of signalling behaviour between cats, the full subtleties of what is being communicated is difficult to appreciate.</p>
            <p>Some studies have suggested that allogrooming behaviour (which most often concentrates on the head and neck area), is quite often associated with agonistic behaviour and thus allogrooming may be a way of redirecting potential aggression in situations where attempts are being made to avoid overt aggression. However, allogrooming largely occurs among cats that are related and/or have strong familiarity thus probably enhancing social bonds.</p>
            <p>Tactile communication in part overlaps with olfactory communication (see below) as there is transfer and exchange of scent marking during a number of tactile communications.</p>
            <h3 className="article-subtitle">Vocal communication</h3>
            <p>Cats display a wide range of vocal communications, and they have been classified in different ways. Cats are said to have one of the widest ‘vocabularies’ (i.e. different patterns of vocalisation) of all carnivore species, and this may be related to the fact that in the natural environment vocal communication is important when they spend much active time in poor lighting conditions. Vocal communications are generally used for either 1) agonistic interactions, 2) sexual interactions, 3) mother-kitten interactions, and 4) cat- human interactions.</p>
        </div>),
    },

    "Play with your cat": {
        title: "Playing With Your Cat",
        text: (<div>
            <p>Most cats enjoy interacting with their owner and playing is a great way to develop the bond between you and your pet.</p>
            <p>Play for a kitten, like any other young animal, is essential for its development to maturity and for the majority of adult cats, it is a pleasurable part of domestic life. As a cat ages, its mobility and energy may lessen but gentle games can still be enjoyed by both cat and owner.</p>
            <p>Owners’ involvement in play can range from a simple game of ball to focused training (involving reinforcing desired behaviours with rewards) over a period of months. Much will depend on the nature of the cat and the time you wish to devote to your pet.</p>
            <p>Cats which never go outside will need plenty of stimulation and play, particularly when young, to prevent them from becoming bored. The owner of such a cat needs to be aware of their responsibility to ensure that the cat’s mental needs, as well as it physical ones, are met. A cat which has access to the great outdoors will find plenty of interest – walls and trees to climb, prey to stalk, leaves to chase and possibly other feline company.</p>
            <p>Cats vary in their motivation to play but all cats, if provided with the right opportunity, will play and benefit from the opportunity to do so, no matter what age. Understanding the specific likes and dislikes of your own individual will enable you to provide the best possible opportunities for play. Your cat’s receptivity to play will depend on its routines and natural activity rhythms.</p>
            <h3 className="article-subtitle">Games to play</h3>
            <p>Toys can appeal to all the feline senses – sight, sound, scent, touch and taste. Movement is a great stimulus and most toys are designed to be used actively in one way or another. Gentle noise (for example, a tinkling bell firmly concealed in a ball) may attract, but some cats will be alarmed by more strident noises. Catnip (dried catmint plant) rubbed on a plastic toy or secreted within a stuffed toy is of particular importance for blind cats and will appeal to the majority. Some cat toys feature different fabrics which encourage cats to rake their claws or rub their necks.</p>
            <p>Establishing what stimulates your cat is based on trial and error, although some commercially available toys have majority appeal, such as those that contain high quality dried catnip (using the dried flowers and leaves of the catmint plant only), fishing rod toys with feathers on the end, small objects on wire that move erratically and small, fur mice. Even simple toys, such as a ping pong ball, can provide hours of fun and exercise. The ball is light enough not to do any damage around the house and the right size for a small paw to bat. For example, if you have stairs in your home, throw the ball up to encourage your cat to chase it or drop it gently from the top so that your cat sees it bounce from step to step. Even everyday household rubbish, such as screwed up balls of paper, sweet wrappers, string and corks can be transformed into exciting toys that can be chased or tossed from paw to paw.</p>
            <h3 className="article-subtitle">Rules of the game</h3>
            <p>It may be possible to identify, particularly if your cat has a high motivation to play, a particularly powerful toy that promotes an instant response every time. This toy should be used randomly to maintain its power. Cats are naturally neophilic (excited by novelty) so toys left out will soon lose their appeal. All toys should, therefore, be rotated randomly and kept in a sealed bag when not in use.</p>
            <p>Games should be ended on a positive note before your cat gets bored; a strong signal, particularly for the enthusiastic player, that the game has stopped is essential. If your cat appears to become over-excited or over-stimulated by a particular toy, stop that activity and redirect its attention to something else. Any toys that are interactive and require your involvement should not be left out.</p>
            <p>Play should mimic natural predatory behaviour so short bursts of activity at frequent intervals would be most beneficial.</p>
            <h3 className="article-subtitle">Interventions</h3>
            <p>It may be necessary on occasions to intervene in social play between cats that has escalated and risks injury to either party. It is advisable not to physically intervene using arms or legs as, in a heightened state of arousal, the cats will not distinguish between you and each other and injury is inevitable. If the escalation has not progressed to physical fighting but has reached the stage of direct staring then an opportunity to break the stare, and therefore the view of each other, can be sufficient to diffuse the situation. A suitable intervention would be to use distraction with a fishing rod toy, laser pointer (leading the cat towards a favourite toy) or kick toy (one large enough to be held in the forelegs and kicked with the hind legs) to gain the cats’ attention by triggering the peripheral vision with rapid movements.</p>
            <p>If the encounter has escalated beyond this point then physical contact can be interrupted by using a blanket or towel thrown over the cats. If the problem persists it may be necessary to seek advice from your veterinarian who may refer you to an animal behaviourist or pet behaviour counsellor to assess the situation and recommend action for long-term management.</p>
        </div>),
    },

};

export default subpageList;